version: '3.8'

services:
  db:
    image: mariadb:11.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=notSecuredToChange
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - test
    volumes:
      - db_data:/var/lib/mysql

  admin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "${PMA_CUSTOM_PORT}:80"
    environment:
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - test

  php:
    image: php:8.1-apache
    restart: unless-stopped
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - db
    networks:
      - test
    ports:
      - "${PHP_CUSTOM_PORT}:80"  # Map host port to the container port
    # Add the following line to bind the service to all network interfaces
    # accessible from the host (0.0.0.0).
    extra_hosts:
      - "php-service:0.0.0.0"

volumes:
  db_data:

networks:
  test:
