name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ahoetatou.com
          port: 22
          user: naiki
    key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAgEAwmhdtpqgKGFt8UJvYaHo7TdGOAZiIR22H/alTdzldrE4q9F5pqA5
      h/0qlgGMLLcLL+gAV3HZVVIlFxIzzc+P5+OcBtshIh7QyQC1m7OVAnTGT2jyX1lLL5u/uW
      hlEEGtfsyKC8KOcB85wsIq6QPFx8D9cxj3meVZLoeM7H3JpdAU9TTODrz2m+t+s5NBq+kP
      KgZfGzihfpTFpZHiS+VNcX0iEU0rohNKLehR9N6Q4xp0jJ7n6/HdjrSgjQUXDALWzNDOjC
      kmjq1YpFKlGd64UptVgj3vnBTFefZmGubqm031y7QQhaWcXgI4ypWgLElCHwmkR1jOUcjg
      gYSlK37VeWAulcksTL4YXREkjXq3mnbCV9R5nuPVcozK8AfoL9O9JoT5VQ5LtdyZkEH7ac
      1S8y2OYCqoTpBtfEOXxJfVBuHdECGd/GDlVYcTlQspJ//2kqJzJgj9ZEym7QrE/D9AIxbB
      etKIRftMduU1vTRM9bfdKpXbEquHozjTmZSqmfpi+dGo4jkdyXWjFYUd0US3HZumyBUyFy
      f0qeBvdov21miJ+Snk2Av72+yGtljSeUKR1g72Lpz/rltN7t20hAszG4wGzuvF+GzKcOMZ
      OTdtvP0xEqPYn10QW62jvCJx3cH5H7o1zvnpRpc4e2zs/BTUogCRAKiodVSvuQCfxRu8nd
      sAAAdI+cTlgvnE5YIAAAAHc3NoLXJzYQAAAgEAwmhdtpqgKGFt8UJvYaHo7TdGOAZiIR22
      H/alTdzldrE4q9F5pqA5h/0qlgGMLLcLL+gAV3HZVVIlFxIzzc+P5+OcBtshIh7QyQC1m7
      OVAnTGT2jyX1lLL5u/uWhlEEGtfsyKC8KOcB85wsIq6QPFx8D9cxj3meVZLoeM7H3JpdAU
      9TTODrz2m+t+s5NBq+kPKgZfGzihfpTFpZHiS+VNcX0iEU0rohNKLehR9N6Q4xp0jJ7n6/
      HdjrSgjQUXDALWzNDOjCkmjq1YpFKlGd64UptVgj3vnBTFefZmGubqm031y7QQhaWcXgI4
      ypWgLElCHwmkR1jOUcjggYSlK37VeWAulcksTL4YXREkjXq3mnbCV9R5nuPVcozK8AfoL9
      O9JoT5VQ5LtdyZkEH7ac1S8y2OYCqoTpBtfEOXxJfVBuHdECGd/GDlVYcTlQspJ//2kqJz
      Jgj9ZEym7QrE/D9AIxbBetKIRftMduU1vTRM9bfdKpXbEquHozjTmZSqmfpi+dGo4jkdyX
      WjFYUd0US3HZumyBUyFyf0qeBvdov21miJ+Snk2Av72+yGtljSeUKR1g72Lpz/rltN7t20
      hAszG4wGzuvF+GzKcOMZOTdtvP0xEqPYn10QW62jvCJx3cH5H7o1zvnpRpc4e2zs/BTUog
      CRAKiodVSvuQCfxRu8ndsAAAADAQABAAACAEWDPtr/r/uwVrj4+c2NsLU9WejHc4gG0Svd
      q97K+Ot3U92v4ZEwYlHbNsJ7XC1S5/ehu5mI1l65KBT3R7m0GW8fhhc3fEHwhdQRYl6BmG
      rP6WbUjjGEwqsLxEKd7uEgstIPfd7VmsvBhow6lFBMLoiN27Ivf70x8jD+e+fF1HfrDstc
      rb88VuuKiXvZUBaRl3/91jzsA2a4+HEK2EEuBQJq7WcFUnA5+ICwvLlTabgiqgDsAt5tVb
      zknjG+W67KRxbmJKyePDCxD+x1tp4o8nxrGWigD9Cd5ryE256L6eBNQHGteWjoPiCpJ7hc
      RvD+4tspPena+a7ppkj5bnu+dsK3TGSCTkiYhw2pQiRo032pxECbpUOL5KjFuHbgfGSoSo
      4LQjq7enJJn/i63LP8UzabLXfgHiWWDGuW9WT5YNWzLn/B+mIsGNs1CHtMPbYCejqatrmv
      b7vT1O/5RPWMOApiHp5PPsbbIp4UwqURcb2a/swAd5gzHI3dhC8hER2EiwOsPVMwsZrmkN
      cUH5iHs8qu4XLG7e3RZlhGGZQfL29tnBWtD9g1raGcYEhCZ8RrDJWia7tahWprF09F8A3F
      ghiz62mHlBdfxrwO10S/hJu9fgFhoc2bkDnDyWWLfHC5h2QoDZTMUhPN5yjApvHP38YSqQ
      YP5/pNl8v3+aR9lkDpAAABAA20wIcaBG0GhQW81HUs6HAikGd3gvun/XgZoa4AWLRi8RfO
      WRUtT93I9d97zrnPmNX1oqOq+a5tG6beunaUo/axnI2Cy1nm/PYfFvw6rIRjNxOzUh+CJG
      ozIj7pEDi9TuhYaW6WT48WP1fdSflafuBcxq4blASaVmqBdAykE4iC5+mpfWhSTmThvZVU
      2ocoNp14JJ65uNRi0RwUTVR4f5CCxJZWMW9B79tpdIKo09XHimXm8LjQ2vAOtXR4FVqbQI
      kMBxJv4jMIrA7SI4GAOBsKQpKw0zvA+MnxD7+ITyTNeBoesL0CF992+e6zeZdmePXn1Z25
      kLLIEQKrxhP1eT0AAAEBAOzSb+oKzKrKEAN9gzl13oe+8152JpGsSm8Jc51DE4Z1g41NlJ
      pbTb/MuP83Pt/2i93yYpXffe8pznh4APFbb+CbsXDMHNPTK/90k8B5+6lSRanaEVswoIP6
      LG5lSWszvpa3fi37z2llM7IerrG3OTWdkK/L0ipCVdMZc/pJ/7bWCQV+KmctrYqIMQlssi
      NUQH1hhNXv+Rbvn1z6Qd0QaSznKdBu03rKAfzeWSHNkbAg7hJl5XoFZRoy/mO3Nqdzv8Sl
      WYCP/rYKQWAxIuAIt2F8QbYISkybP2drtdgkHy/McBUy8M9gCjmrzTsdQaTkyg/wGX9Qpl
      uBZatWomGky7MAAAEBANImot+WJICqDHE3If6H5D4Kz8HkK0u6vDXisKcb+pNpunfZ1N/A
      V2AWRCcjjSptScWxGJ5TpxC/x7D+JnRIxzhbRGPgdhjGBp29wQUxd6OhPEYIbLkwh7m+WT
      U4PFVcckkATvuBy1Qw5Deyn7ZoUpIu1QDCEX6Um/Xam4fV8/aln0rTbosnl/3rgBToEgBX
      Z7iqX3o4nw9MG9RZoqQk74S3KinaB2mqgnU431GN9zZm3rj2zc/yw+jPiMXQJLpU0JE+MH
      rJs/OFz+pY78voA+AmukO3glZFwounRVp3eUyDVP5RD9G4k22+3E8gEVJwkV5CtvaWUmOl
      F0Rg9mG6MTkAAAASbmFpa2licm9AZ21haWwuY29tAQ==
      -----END OPENSSH PRIVATE KEY-----
    pass: ninja
    connect_timeout: 30s
    first_ssh: |
      # optional pre-commands
    scp: |
      # optional scp commands
    last_ssh: |
      cd ~/ahoetatou/a-hoe-tatou/
      git remote update
      git pull origin master
      git checkout master
      ./scripts/rebuild.sh
