name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ahoetatou.com
          port: 22
          user: naiki
          key: ${{ secrets.SERVER_KEY }}
          pass: ninja
          connect_timeout: 30s
          first_ssh: |
            # optional pre-commands
          scp: |
            # optional scp commands
          last_ssh: |
            cd ~/ahoetatou/a-hoe-tatou/
            git remote update
            git fetch --all
            git reset --hard origin/master
            ./scripts/rebuild.sh
